import type { Theme } from '../types'

export const themes: Theme[] = [
  {
    id: 'editorial-noir',
    label: 'Editorial Noir',
    category: 'dark',
    vars: {
      '--bg': '#0a0a0a',
      '--surface': '#111111',
      '--surface-2': '#1a1a1a',
      '--accent': '#c8b89a',
      '--accent-2': '#c8b89a',
      '--text': '#f5f0e8',
      '--text-muted': '#6b6b6b',
      '--border': '#2a2a2a',
      '--font-display': "'Playfair Display', Georgia, serif",
      '--font-body': "'DM Mono', 'Courier New', monospace",
      '--radius': '0px',
    },
  },
  {
    id: 'chaos-theory',
    label: 'Chaos Theory',
    category: 'dark',
    vars: {
      '--bg': '#0e0e0e',
      '--surface': '#141414',
      '--surface-2': '#1a1a1a',
      '--accent': '#ff2d55',
      '--accent-2': '#c8ff00',
      '--text': '#f5f0e8',
      '--text-muted': '#888888',
      '--border': '#2a2a2a',
      '--font-display': "'Bebas Neue', 'Arial Black', sans-serif",
      '--font-body': "'Space Mono', 'Courier New', monospace",
      '--radius': '0px',
    },
  },
  {
    id: 'organic-cream',
    label: 'Organic Cream',
    category: 'light',
    vars: {
      '--bg': '#f7f3ec',
      '--surface': '#eee8de',
      '--surface-2': '#e5ddd2',
      '--accent': '#d4a853',
      '--accent-2': '#b8883a',
      '--text': '#2c1810',
      '--text-muted': '#8b6f47',
      '--border': '#d5ccc0',
      '--font-display': "'Cormorant Garamond', Georgia, serif",
      '--font-body': "'Inter', system-ui, sans-serif",
      '--radius': '4px',
    },
  },
  {
    id: 'cyber-minimal',
    label: 'Cyber Minimal',
    category: 'dark',
    vars: {
      '--bg': '#070a0f',
      '--surface': 'rgba(13,17,23,0.8)',
      '--surface-2': '#0d1117',
      '--accent': '#00d4ff',
      '--accent-2': '#7c3aed',
      '--text': '#e8edf5',
      '--text-muted': '#6b7280',
      '--border': '#1e2530',
      '--font-display': "'Space Grotesk', system-ui, sans-serif",
      '--font-body': "'JetBrains Mono', 'Courier New', monospace",
      '--radius': '8px',
      '--glass-blur': '12px',
    },
  },
  {
    id: 'warm-brutalist',
    label: 'Warm Brutalist',
    category: 'light',
    vars: {
      '--bg': '#fffbf0',
      '--surface': '#fffbf0',
      '--surface-2': '#f5f0e0',
      '--accent': '#ff6b35',
      '--accent-2': '#ffd60a',
      '--text': '#1a1a1a',
      '--text-muted': '#555555',
      '--border': '#1a1a1a',
      '--font-display': "'Syne', system-ui, sans-serif",
      '--font-body': "'IBM Plex Mono', 'Courier New', monospace",
      '--radius': '0px',
    },
  },
]
